export * from "./DesktopHeroSection";
export * from "./DesktopFeaturesSection";
export * from "./DesktopTechSpecsSection";
export * from "./DesktopColorSelectorSection";
export * from "./DesktopGallerySection";
export * from "./DesktopFaqSection";
export * from "./DesktopOrderSection";
export * from "./DesktopContactSection";
export * from "./DesktopBlogSection";
